export const GET_TODO_LIST_ITEMS_REQUEST = "GET_TODO_LIST_ITEMS_REQUEST" as const;
export const GET_TODO_LIST_ITEMS_SUCCESS = "GET_TODO_LIST_ITEMS_SUCCESS" as const;
export const GET_TODO_LIST_ITEMS_FAILURE = "GET_TODO_LIST_ITEMS_FAILURE" as const;

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST" as const;
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS" as const;
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE" as const;

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST" as const;
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS" as const;
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE" as const;